# Generated by Django 2.1.7 on 2019-06-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0010_auto_20190421_2025'),
        ('ucmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucmanage.UnidadeCurricular')),
                ('horaINI', models.TimeField()),
                ('Duracao', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExameAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunoID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.Profile')),
                ('exameID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examemanage.Exame')),
            ],
        ),
    ]
