# Generated by Django 2.1.7 on 2019-06-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examemanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examealuno',
            name='inscrito',
            field=models.BooleanField(default=False),
        ),
    ]
