# Generated by Django 2.1.7 on 2019-06-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examemanage', '0002_examealuno_inscrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame',
            old_name='Duracao',
            new_name='horaFim',
        ),
    ]
