# Generated by Django 2.1.7 on 2019-04-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20190417_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='id_type',
            field=models.CharField(choices=[('cc', 'cartao cidadao'), ('pp', 'passport')], max_length=2),
        ),
    ]
