# Generated by Django 2.1.7 on 2019-04-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20190417_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.Family'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.Identification'),
        ),
    ]
