# Generated by Django 2.1.7 on 2019-06-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0010_auto_20190421_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
