# Generated by Django 2.1.7 on 2019-06-25 23:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0011_profile_is_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chairs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=[], size=None),
            preserve_default=False,
        ),
    ]
