# Generated by Django 2.1.7 on 2019-06-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucmanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='alunoID',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='aulaID',
        ),
        migrations.DeleteModel(
            name='Presenca',
        ),
    ]
