# Generated by Django 2.1.7 on 2019-06-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucmanage', '0002_auto_20190625_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professoraula',
            old_name='aulaID',
            new_name='aula',
        ),
        migrations.RenameField(
            model_name='professoraula',
            old_name='profID',
            new_name='prof',
        ),
    ]
