# Generated by Django 2.2.2 on 2019-06-28 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucmanage', '0003_auto_20190627_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='professoraula',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucmanage.UnidadeCurricular'),
        ),
    ]
