# Generated by Django 2.1.7 on 2019-06-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
